spring.datasource.url=jdbc:postgresql://localhost:5433/digibank_db
spring.datasource.username=digibank_user
spring.datasource.password=digibank_pwd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=INFO
